"""empty message

Revision ID: 37e903573c6f
Revises: 
Create Date: 2020-02-21 09:56:44.495347

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37e903573c6f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('questionario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titolo', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('domanda',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('domanda', sa.String(), nullable=False),
    sa.Column('questionario_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['questionario_id'], ['questionario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('risposta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('risposta', sa.String(), nullable=False),
    sa.Column('esatta', sa.Boolean(), nullable=False),
    sa.Column('domanda_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['domanda_id'], ['domanda.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('risposta')
    op.drop_table('domanda')
    op.drop_table('questionario')
    op.drop_table('user')
    # ### end Alembic commands ###
